### ISSUE TITLE
UUID Dependency

### ISSUE THREAD

**Issue by gtilson** [Canardoux/flutter_sound#641]
The latest version of Flutter Sound depends on uuid ^2.2.2; however some of my other dependencies depends on newer versions of uuid. Could you please update this dependency so I can continue using flutter sound?

**Comment by hey24sheep** [comment]
I am facing the same issue.

**Comment by Larpoux** [comment]
I am currently working on a new version of Flutter Sound which will be Null Safety compliant and will depend on uuid: ^3.0.1
I will release this version later this week.

**Comment by hey24sheep** [comment]
@Larpoux also other packages are outdated like `synchronized`

**Comment by Larpoux** [comment]
```
dependencies:
  path_provider: ^2.0.1
  logger: ^1.0.0-nullsafety.0
  recase: ^4.0.0-nullsafety.0
  uuid: ^3.0.1
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  path: ^1.8.0
  synchronized: ^3.0.0
  flutter:
    sdk: flutter
```

**Comment by Larpoux** [comment]
Flutter Sound V8 is released and is Null Safety compliant.
Tell me if any problem ...

**Comment by tigrenok00** [comment]
I need uuid ^4.0.0 and facing the same problem

**Comment by sauravdpl** [comment]
I also  need uuid ^4.0.0

**Comment by khylenko** [comment]
Need uuid ^4.1.0

**Comment by Er-Dong-Chen** [comment]
需要 logger ^2.0.0

**Comment by bayasdev** [comment]
2024 and still using old uuid

**Comment by Larpoux** [comment]
I think that Flutter Sound dependencies are now up to date :
```yaml
dependencies:
  path_provider: ^2.1.2
  recase: ^4.1.0
  uuid: ^4.3.3
  provider: ^6.1.1
  path: ^1.9.0
  synchronized: ^3.1.0
  logger: ^2.0.2
 ```
